### ISSUE TITLE
Remove the name of the cases for training

### ISSUE THREAD

**Issue by esgomezm** [westgate458/XB-Net#1]
Hey,

Please, add a note in the README that points to this line so it can be changed before running the code. Another chance would be reading the name of the datasets in datasets/pre.

https://github.com/westgate458/XB-Net/blob/c987139b37e67ec78336cc2c05b6d0ead0c742a9/train_model.py#L61

**Comment by westgate458** [comment]
Additional comments added in `train_model.py`
`cases = ['DIC-C2DH-HeLa','Fluo-N3DH-CHO'] # change the names for the cases used for training`
Also the README file has been updated to reflect this change.

**Future work:** automatic detection of folders under `./datasets/pre/GT+ST/`
